# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_recurso_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='archivo',
        ),
    ]
